pagseguro:
   email: seuemail@email.com
   token: TOKENDESEGURANÇA
defaultcmd: '/ativarvip <código>'
itens:
   vip1:
      id: 003
      valor: 50.0
      nome: '&bVIPLite'
      descricao: '&4VIP LITE ESTA EM PROMOÇÃO'
      texto: 'Texto informatico, para labels'
      visivel: true
      