PagSeguro:
   Email: seuemail@email.com
   Token: TOKENDESEGURANÇA
Itens:
   vip1:
      ID: 003
      Valor: 50.0
      Nome: '&bVIPLite'
      Descricao: '&4VIP LITE ESTA EM PROMOÇÃO'
      Texto: 'Texto informatico, para labels'
      Visivel: true